/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSnackbar: typeof import('./components/AppSnackbar.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./components/SidePanel.vue')['default']
  }
}
